project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!*.md"
    - "!*.markdown"

website:
  title: "Daniel Huang"
  description: "Founder of Base26 Labs developing neuro-symbolic AI to solve problems in the physical world with digital intelligence. Harvard PhD, former SFSU professor of CS."
  favicon: favicon.ico

  navbar:
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "LBAI Lab"
        href: lbai.qmd
    right:
      - icon: github
        href: https://github.com/danehuang
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-huang-28258313b
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=VTe4SGUAAAAJ&hl=en
        aria-label: "Google Scholar"

  page-footer:
    left: "Â© 2026 Daniel Huang"
    right:
      - icon: github
        href: https://github.com/danehuang
        aria-label: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-huang-28258313b
        aria-label: "LinkedIn"
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=VTe4SGUAAAAJ&hl=en
        aria-label: "Google Scholar"

format:
  html:
    theme: litera
    toc: false
    code-copy: true
    code-overflow: wrap
